services:
  shop_api:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000" # host:container
    depends_on:
      - shop_data
  shop_data:
    image: "postgres:14"
    environment:
      POSTGRES_DB: products_gk_kg
      POSTGRES_USER: products_gk_kg_user
      POSTGRES_PASSWORD: 20092009
    volumes:
      - "data_shop:/var/lib/postgresql/data"
volumes:
  data_shop: